openapi: 3.1.0
info:
  title: PA Vietnam Support API
  version: 1.0.0
  license:
    name: API
  description: API cho hệ thống ticket hỗ trợ khách hàng
  contact:
    name: PA Vietnam
    email: dev@pavietnam.vn
servers:
  - url: https://apigateway.pavietnam.vn
    description: Production
security:
  - bearerAuth: []
tags:
  - name: Ticket
    description: Các API liên quan đến ticket hỗ trợ khách hàng
  - name: Account
    description: Các API liên quan đến tài khoản
paths:
  /v1/users/{user_id}/tickets:
    get:
      summary: Hiển thị danh sách ticket của khách hàng
      operationId: listUserTickets
      description: Lấy danh sách tất cả các ticket thuộc về một khách hàng cụ thể. API này hỗ trợ phân trang và lọc theo trạng thái ticket.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_UPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Số thứ tự trang muốn hiển thị
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Tổng số ticket muốn hiển thị trên một trang
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - CREATED
              - IN_PROGRESS
              - PENDING
              - CLOSED
          description: 'Tìm kiếm theo trạng thái:CREATED: Mới tạoIN_PROGRESS: Đang xử lýPENDING: Chờ phản hồiCLOSED: Đóng'
        - name: keyword
          in: query
          required: false
          schema:
            type: string
          description: 'Nội dung cần tìm kiếm- Tìm kiếm theo: Mã ticket, tiêu đề.- Tối thiểu 4 ký tự'
        - name: date_from
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Tìm kiếm từ ngày (Y-m-d H:i:s)- date_to>=data_from
        - name: date_to
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Tìm kiếm đến ngày (Y-m-d H:i:s)- date_to>=data_from
        - name: sort_type
          in: query
          required: false
          schema:
            type: string
            enum:
              - LAST_UPDATED_DESC
              - CREATED_DATE_DESC
          description: 'Kiểu sắp xếp:LAST_UPDATED_DESC:Ngày cập nhật giảm dầnCREATED_DATE_DESC: Ngày tạo giảm dần'
        - name: post_by
          in: query
          required: false
          schema:
            type: string
            enum:
              - USER
              - SYSTEM
          description: 'Người tạo ticketUSER: user hiện tại (khách hàng)SYSTEM: hệ thống'
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required: &ref_2
                      - success
                      - error
                      - data
                    properties: &ref_3
                      success:
                        type: boolean
                        example: true
                      error:
                        type:
                          - 'null'
                        example: null
                      data:
                        description: Dữ liệu trả về tuỳ vào từng endpoint khác nhau
                  - type: object
                    properties:
                      data:
                        type: object
                        properties: &ref_9
                          current_page:
                            type: integer
                            description: Số thứ tự trang hiện tại
                          next_page_url:
                            type: string
                            description: Link đến trang tiếp theo
                          prev_page_url:
                            type: string
                            description: Link đến trang trước
                          first_page_url:
                            type: string
                            description: Link đến trang đầu tiên
                          per_page:
                            type: integer
                            description: Số record mỗi trang
                          from:
                            type: integer
                            description: Số thứ tự bắt đầu
                          to:
                            type: integer
                            description: Số thứ tự kết thúc
                          data:
                            type: array
                            items:
                              type: object
                              properties: &ref_8
                                id:
                                  type: integer
                                  description: Id của ticket
                                  readOnly: true
                                title:
                                  type: string
                                  description: Tiêu đề
                                code:
                                  type: string
                                  description: Mã ticket
                                created_date:
                                  type: string
                                  description: Ngày ticket được tạo (Y-m-d H:i:s)
                                last_updated:
                                  type: string
                                  description: Ngày cập nhật gần nhất (Y-m-d H:i:s)
                                trangthai:
                                  type: integer
                                  description: Trạng thái thực của ticket
                                status:
                                  type: string
                                  description: 'Trạng thái dành cho FEGồm 4 trạng thái: CREATED: Vừa tạoIN_PROGRESS: Đang xử lýPENDING: Chờ phản hồiCLOSED: Đóng'
                                department:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: Id của phòng ban
                                      readOnly: true
                                    name:
                                      type: string
                                      description: Tên phòng ban
                                  description: Thông tin phòng ban xử lý yêu cầu (xem thêm bên dưới)
                                service:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: Id của dịch vụ
                                      readOnly: true
                                    domain:
                                      type: string
                                      description: Tên domain
                                    type:
                                      type: string
                                      description: Loại dịch vụ
                                  description: Thông tin về dịch vụ yêu cầu (xem thêm bên dưới)
                            description: Danh sách các ticket
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: &ref_4
            application/json:
              schema:
                type: object
                required: &ref_0
                  - success
                  - error
                properties: &ref_1
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                        description: 'Mã lỗi nội bộ của hệ thống: 4102: Token không hợp lệ hoặc đã hết hạn 4108: Không có quyền truy cập 4004: Không tìm thấy dữ liệu 4200: Dữ liệu không hợp lệ'
                        example: 4200
                      message:
                        type: string
                        example: Dữ liệu không hợp lệ
                      data:
                        type:
                          - object
                          - 'null'
              example:
                success: false
                error:
                  code: 4102
                  message: Token không hợp lệ hoặc đã hết hạn
                  data: null
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: &ref_5
            application/json:
              schema:
                type: object
                required: *ref_0
                properties: *ref_1
              example:
                success: false
                error:
                  code: 4108
                  message: IP không được phép truy cập
                  data: null
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: &ref_6
            application/json:
              schema:
                type: object
                required: *ref_0
                properties: *ref_1
              example:
                success: false
                error:
                  code: 4004
                  message: Không tìm thấy dữ liệu
                  data: null
        '500':
          description: Lỗi server không mong muốn
          content: &ref_7
            application/json:
              schema:
                type: object
                required: *ref_0
                properties: *ref_1
              example:
                success: false
                error:
                  code: 500
                  message: Lỗi hệ thống, vui lòng thử lại sau
                  data:
                    type:
                      - null
    post:
      summary: Tạo ticket hỗ trợ mới cho khách hàng
      operationId: createUserTicket
      description: Tạo ticket yêu cầu hỗ trợ mới cho khách hàng trong hệ thống. Ticket sẽ được gán cho bộ phận chăm sóc khách hàng để xử lý theo quy trình.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties: &ref_10
                department_id:
                  type: integer
                  description: Phòng ban muốn được hỗ trợ
                service_id:
                  type: integer
                  description: Dịch vụ cần hỗ trợ
                title:
                  type: string
                  description: Tiêu đề
                descriptions:
                  type: string
                  maxLength: 4000
                  description: Nội dung yêu cầu -  Tối đa 4000 ký tự
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  maxItems: 3
                  description: 'Tệp đính kèm -  Tối đa 3 files -  Tối đa 10MB mỗi file -  Chỉ chấp nhận định dạng: .gif, .jpg, .jpeg, .png, .svg, .bmp, .pdf, .zip, .rar'
              required: &ref_11
                - department_id
                - service_id
                - title
                - descriptions
  /v1/users/{user_id}/tickets/{id}:
    get:
      summary: Xem chi tiết ticket của khách hàng
      operationId: getUserTicketDetails
      description: Hiển thị thông tin chi tiết của một ticket cụ thể cho khách hàng. API chỉ trả về ticket thuộc về user_id được chỉ định để đảm bảo phân quyền đúng.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required: *ref_2
                    properties: *ref_3
                  - type: object
                    properties:
                      data:
                        type: object
                        properties: &ref_13
                          id:
                            type: integer
                            description: Id của ticket
                            readOnly: true
                          title:
                            type: string
                            description: Tiêu đề
                          descriptions:
                            type: string
                            description: Nội dung yêu cầu hỗ trợ
                          code:
                            type: string
                            description: Mã ticket
                          created_date:
                            type: string
                            description: Ngày ticket được tạo (Y-m-d H:i:s)
                          last_updated:
                            type: string
                            description: Ngày cập nhật gần nhất (Y-m-d H:i:s)
                          trangthai:
                            type: integer
                            description: Trạng thái thực của ticket
                          status:
                            type: string
                            description: 'Trạng thái dành cho FEGồm 4 trạng thái: CREATED: Vừa tạoIN_PROGRESS: Đang xử lýPENDING: Chờ phản hồiCLOSED: Đóng'
                          files:
                            type: array
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  description: Đường dẫn đến file
                                category:
                                  type: string
                                  description: 'Phân loại:image:Các file ảnhvideo: Các file videodocument: Tài liệu (PDF, Word, Excel, …)archive: File nénother: Loại khác'
                            description: Thông tin các tệp tin (xem thêm bên dưới)
                          department:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: Id của phòng ban
                                readOnly: true
                              name:
                                type: string
                                description: Tên phòng ban
                            description: Thông tin phòng ban xử lý yêu cầu (xem thêm bên dưới)
                          service:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: Id của dịch vụ
                                readOnly: true
                              domain:
                                type: string
                                description: Tên domain
                              type:
                                type: string
                                description: Loại dịch vụ
                            description: Thông tin về dịch vụ yêu cầu (xem thêm bên dưới)
                          assignee:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: Id của dịch vụ
                                readOnly: true
                              name:
                                type: string
                                description: Tên nhân viên
                              mgroup:
                                type: integer
                                description: 'Phân loại người dùng:   1 - Khách hàng PA   2 - Đại lý, tài khoản trả trước   3 - Nhân viên   4 - Khách hàng đại lý'
                            description: Thông tin về nhân viên hỗ trợ (xem thêm bên dưới)
                          conversations:
                            type: array
                            items:
                              type: object
                              properties: &ref_12
                                id:
                                  type: integer
                                  description: Id cuộc trao đổi
                                  readOnly: true
                                descriptions:
                                  type: string
                                  description: Nội dung
                                files:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      url:
                                        type: string
                                        description: Đường dẫn đến file
                                      category:
                                        type: string
                                        description: 'Phân loại:image:Các file ảnhvideo: Các file videodocument: Tài liệu (PDF, Word, Excel, …)archive: File nénother: Loại khác'
                                  description: Thông tin các tệp tin (xem thêm bên dưới)
                                created_date:
                                  type: string
                                  description: Ngày tạo (Y-m-d H:i:s)
                                owner:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: Id người tạo
                                      readOnly: true
                                    name:
                                      type: string
                                      description: Tên người tạo
                                    mgroup:
                                      type: integer
                                      description: 'Phân loại người dùng:   1 - Khách hàng PA   2 - Đại lý, tài khoản trả trước   3 - Nhân viên   4 - Khách hàng đại lý'
                                  description: Thông tin người tạo (xem thêm bên dưới)
                            description: Danh sách các phản hồi (xem thêm bên dưới)
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
  /v1/users/{user_id}/tickets/{id}/close:
    put:
      summary: Đóng ticket của khách hàng
      operationId: closeUserTicket
      description: API cho phép đóng một ticket cụ thể của khách hàng khi vấn đề đã được giải quyết. Ticket phải tồn tại và thuộc về user_id được chỉ định.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
  /v1/users/{user_id}/tickets/{id}/reopen:
    post:
      summary: Mở lại ticket đã đóng của khách hàng
      operationId: reopenUserTicket
      description: API cho phép mở lại ticket đã đóng trước đó của khách hàng. Chỉ áp dụng cho các ticket ở trạng thái đã đóng và trong thời gian cho phép mở lại.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties: &ref_14
                descriptions:
                  type: string
                  maxLength: 4000
                  description: Nội dung -  Tối đa 4000 ký tự
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  maxItems: 3
                  description: 'Tệp đính kèm -  Tối đa 3 files -  Tối đa 10MB mỗi file -  Chỉ chấp nhận định dạng: .gif, .jpg, .jpeg, .png, .svg, .bmp, .pdf, .zip, .rar'
  /v1/users/{user_id}/tickets/{ticket_id}/feedback/{id}:
    post:
      summary: Chỉnh sửa feedback của ticket khách hàng
      operationId: updateTicketFeedback
      description: Cho phép cập nhật nội dung feedback đã gửi cho một ticket cụ thể của khách hàng. API yêu cầu quyền truy cập vào ticket và feedback phải thuộc về user_id được chỉ định.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: &ref_15
                id:
                  type: integer
                  description: Id của đánh giá
                review_service:
                  type: integer
                  description: Số sao cho chất lượng dịch vụNhỏ nhất 1Lớn nhất 5
                review_employee:
                  type: integer
                  description: Số sao cho chất lượng phục vụNhỏ nhất 1Lớn nhất 5
              required: &ref_16
                - id
                - review_service
                - review_employee
  /v1/users/{user_id}/tickets/{id}/support-staffs:
    get:
      summary: Lấy danh sách nhân viên hỗ trợ ticket
      operationId: getTicketSupportStaffs
      description: Trả về danh sách các nhân viên đang được phân công hỗ trợ xử lý một ticket cụ thể. API này giúp người dùng biết được ai đang phụ trách giải quyết yêu cầu của họ.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required: *ref_2
                    properties: *ref_3
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties: &ref_17
                            id:
                              type: integer
                              description: id của nhân viên
                              readOnly: true
                            name:
                              type: string
                              description: Tên đầy đủ của nhân viên
                            department:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  description: id phòng ban
                                  readOnly: true
                                name:
                                  type: string
                                  description: Tên phòng ban
                              description: Thông tin phòng ban của nhân viên
                            rating:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  description: id đánh giá
                                  readOnly: true
                                stars:
                                  type: integer
                                  description: Số sao
                                descriptions:
                                  type: string
                                  description: Nội dung đánh giá
                              description: Thông tin đánh giá của nhân viên
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
  /v1/users/{user_id}/tickets/{id}/conversations:
    post:
      summary: Tạo phản hồi ticket cho khách hàng
      operationId: createTicketConversation
      description: API cho phép tạo phản hồi mới trong ticket của khách hàng. Được sử dụng để ghi nhận trao đổi, cập nhật trạng thái hoặc cung cấp giải pháp cho vấn đề của khách hàng.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required: *ref_2
                    properties: *ref_3
                  - type: object
                    properties:
                      data:
                        type: object
                        properties: &ref_18
                          id:
                            type: integer
                            description: Id của phản hồi
                            readOnly: true
                          descriptions:
                            type: string
                            description: Nội dung yêu cầu hỗ trợ
                          files:
                            type: array
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  description: Đường dẫn đến file
                                category:
                                  type: string
                                  description: 'Phân loại:image:Các file ảnhvideo: Các file videodocument: Tài liệu (PDF, Word, Excel, …)archive: File nénother: Loại khác'
                            description: Thông tin các tệp tin (xem thêm bên dưới)
                          created_date:
                            type: string
                            description: Ngày tạo (Y-m-d H:i:s)
                          owner:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: Id người tạo
                                readOnly: true
                              name:
                                type: string
                                description: Tên người tạo
                              mgroup:
                                type: integer
                                description: 'Phân loại người dùng:   1 - Khách hàng PA   2 - Đại lý, tài khoản trả trước   3 - Nhân viên   4 - Khách hàng đại lý'
                            description: Thông tin người tạo (xem thêm bên dưới)
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
  /v1/users/{user_id}/tickets/{ticket_id}/ratings:
    post:
      summary: Tạo đánh giá cho ticket
      operationId: createTicketRating
      description: Cho phép khách hàng tạo đánh giá (rating) cho ticket đã được xử lý. API này giúp thu thập phản hồi về chất lượng dịch vụ hỗ trợ.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: &ref_19
                ratings:
                  type: array
                  items:
                    type: object
                    properties:
                      supporter_id:
                        type: integer
                        description: ID nhân viên hỗ trợ
                      stars:
                        type: integer
                        description: 'Số sao -  Tối thiểu: 1 -  Tối đa: 5'
                      descriptions:
                        type: string
                        maxLength: 4000
                        description: Nội dung đánh giá -  Tối đa 4000 ký tự -  Bắt buộc nếu stars < 3
                    required:
                      - supporter_id
                      - stars
                  description: Danh sách các đánh giáTham khảo bên dưới
                supporter_id:
                  type: integer
                  description: ID nhân viên hỗ trợ
                stars:
                  type: integer
                  description: 'Số sao -  Tối thiểu: 1 -  Tối đa: 5'
                descriptions:
                  type: string
                  maxLength: 4000
                  description: Nội dung đánh giá -  Tối đa 4000 ký tự -  Bắt buộc nếu stars < 3
              required: &ref_20
                - ratings
                - supporter_id
                - stars
  /v1/users/{user_id}/tickets/{id}/feedback:
    post:
      summary: Tiếp nhận phản ánh góp ý của khách hàng
      operationId: submitTicketFeedback
      description: API cho phép khách hàng gửi phản ánh, góp ý về ticket đã được xử lý. Thông tin phản hồi được lưu trữ để đánh giá chất lượng dịch vụ và cải thiện quy trình hỗ trợ.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties: &ref_21
                title:
                  type: string
                  description: Vấn đề bạn gặp phải
                descriptions:
                  type: string
                  maxLength: 4000
                  description: Chi tiết sự việc -  Tối thiểu 20 ký tự -  Tối đa 4000 ký tự
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  maxItems: 3
                  description: 'Tệp đính kèm -  Tối đa 3 files -  Tối đa 10MB mỗi file -  Chỉ chấp nhận định dạng: .gif, .jpg, .jpeg, .png, .svg, .bmp, .pdf, .zip, .rar'
              required: &ref_22
                - title
                - descriptions
  /v1/users/{user_id}/tickets/{id}/change-assignee:
    post:
      summary: Đổi nhân viên được phân công xử lý ticket
      operationId: changeTicketAssignee
      description: Thay đổi nhân viên hỗ trợ được phân công cho một ticket cụ thể của người dùng. Chỉ những người có quyền quản lý hoặc người được phân công hiện tại mới có thể thực hiện thay đổi này.
      tags:
        - Ticket
      security:
        - bearerAuth: []
      x-permission: CHECK_NEWUPDATE
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                required: *ref_2
                properties: *ref_3
              example:
                success: true
                data: null
                error: null
        '401':
          description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
          content: *ref_4
        '403':
          description: IP không hợp lệ - Mã lỗi 4108
          content: *ref_5
        '404':
          description: Không tim thấy dữ liệu - Mã lỗi 4004
          content: *ref_6
        '500':
          description: Lỗi server không mong muốn
          content: *ref_7
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: &ref_23
                reason:
                  type: string
                  maxLength: 4000
                  description: Lý do từ chối.Tối đa 4000 ký tự.
              required: &ref_24
                - reason
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    StandardSuccess:
      type: object
      required: *ref_2
      properties: *ref_3
    ListUserTicketsDataData:
      type: object
      properties: *ref_8
    ListUserTicketsData:
      type: object
      properties: *ref_9
    StandardError:
      type: object
      required: *ref_0
      properties: *ref_1
    CreateUserTicketRequest:
      type: object
      properties: *ref_10
      required: *ref_11
    GetUserTicketDetailsDataConversations:
      type: object
      properties: *ref_12
    GetUserTicketDetailsData:
      type: object
      properties: *ref_13
    ReopenUserTicketRequest:
      type: object
      properties: *ref_14
    UpdateTicketFeedbackRequest:
      type: object
      properties: *ref_15
      required: *ref_16
    GetTicketSupportStaffsDataList:
      type: object
      properties: *ref_17
    CreateTicketConversationData:
      type: object
      properties: *ref_18
    CreateTicketRatingRequest:
      type: object
      properties: *ref_19
      required: *ref_20
    SubmitTicketFeedbackRequest:
      type: object
      properties: *ref_21
      required: *ref_22
    ChangeTicketAssigneeRequest:
      type: object
      properties: *ref_23
      required: *ref_24
  responses:
    Unauthorized:
      description: Token không hợp lệ hoặc đã hết hạn - Mã lỗi 4102
      content: *ref_4
    Forbidden:
      description: IP không hợp lệ - Mã lỗi 4108
      content: *ref_5
    NotFound:
      description: Không tim thấy dữ liệu - Mã lỗi 4004
      content: *ref_6
    InternalError:
      description: Lỗi server không mong muốn
      content: *ref_7
